In [ ]:
/content/drive/MyDrive/car_evaluation.csv

In [28]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
import seaborn as sns

In [29]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
## index_col = 0 : 열 인덱스를 0,1,2,3, 이렇게 인덱스 부여
# header = None: header를 0,1,2,3,4,... 이렇게 인덱스 부여
df = pd.read_csv("/content/drive/MyDrive/car_evaluation.csv", header = None)
df

0      1      2     3      4     5      6
0     vhigh  vhigh      2     2  small   low  unacc
1     vhigh  vhigh      2     2  small   med  unacc
2     vhigh  vhigh      2     2  small  high  unacc
3     vhigh  vhigh      2     2    med   low  unacc
4     vhigh  vhigh      2     2    med   med  unacc
...     ...    ...    ...   ...    ...   ...    ...
1723    low    low  5more  more    med   med   good
1724    low    low  5more  more    med  high  vgood
1725    low    low  5more  more    big   low  unacc
1726    low    low  5more  more    big   med   good
1727    low    low  5more  more    big  high  vgood

[1728 rows x 7 columns]

In [30]:
# 컬럼명이 없을때 컬럼명 주기
df.columns=['buying','maint','doors','persons','lug_boot','safety','class']

In [31]:
df.columns

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class'], dtype='object')

In [32]:
df

buying  maint  doors persons lug_boot safety  class
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    low  unacc
4     vhigh  vhigh      2       2      med    med  unacc
...     ...    ...    ...     ...      ...    ...    ...
1723    low    low  5more    more      med    med   good
1724    low    low  5more    more      med   high  vgood
1725    low    low  5more    more      big    low  unacc
1726    low    low  5more    more      big    med   good
1727    low    low  5more    more      big   high  vgood

[1728 rows x 7 columns]

In [33]:
df.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
class       0
dtype: int64

In [34]:
columns = ['buying','maint','doors','persons','lug_boot','safety','class']

In [39]:
label_encoders = {}
for column in columns:
    label_encoders[column] = LabelEncoder()
    df[column] = label_encoders[column].fit_transform(df[column])

In [47]:
# 데이터 확인
df['class'].value_counts()

class
2    1210
0     384
1      69
3      65
Name: count, dtype: int64

In [42]:
X = df.drop('class', axis=1).values
y = df['class']

In [43]:
X

array([[3, 3, 0, 0, 2, 1],
       [3, 3, 0, 0, 2, 2],
       [3, 3, 0, 0, 2, 0],
       ...,
       [1, 1, 3, 2, 0, 1],
       [1, 1, 3, 2, 0, 2],
       [1, 1, 3, 2, 0, 0]])

In [48]:
y

0       2
1       2
2       2
3       2
4       2
       ..
1723    1
1724    3
1725    2
1726    1
1727    3
Name: class, Length: 1728, dtype: int64

In [57]:
# X 데이터를 표준화한다. 즉 각 특정의 평균을 0, 표준편차를 1로 변환하는 역할을 한다.
scaler = StandardScaler()
X = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [58]:
X_train.shape, X_test.shape, y_trian.shape, y_test.shape

((1382, 6), (346, 6), (1382,), (346,))

In [59]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [60]:
# DT (걸정 트리)
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
y_pred = dt.predict(X_test)
dt_accuracy = accuracy_score(y_test, y_pred)
dt_cm = confusion_matrix(y_test, y_pred)
print(f'DT 정확도 {dt_accuracy:.2f}')
print(dt_cm)

DT 정확도 0.98
[[ 73   4   2   0]
 [  0  17   0   0]
 [  0   0 240   0]
 [  1   0   0   9]]


In [61]:
# RF
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
rf_accuracy = accuracy_score(y_test, y_pred)
rf_cm = confusion_matrix(y_test, y_pred)
print(f'RF 정확도 {rf_accuracy:.2f}')
print(rf_cm)

RF 정확도 0.98
[[ 75   2   1   1]
 [  1  15   0   1]
 [  2   0 238   0]
 [  0   0   0  10]]


In [62]:
# SVM
svm = SVC()
svm.fit(X_train, y_train)
y_pred = svm.predict(X_test)
svm_accuracy = accuracy_score(y_test, y_pred)
svm_cm = confusion_matrix(y_test, y_pred)
print(f'SVM 정확도 {svm_accuracy:.2f}')
print(svm_cm)

SVM 정확도 0.91
[[ 73   1   4   1]
 [  7   8   0   2]
 [ 12   0 228   0]
 [  3   0   0   7]]


In [63]:
# LR
lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
lr_accuracy = accuracy_score(y_test, y_pred)
lr_cm = confusion_matrix(y_test, y_pred)
print(f'lr 정확도 {lr_accuracy:.2f}')
print(lr_cm)

lr 정확도 0.65
[[  9   0  67   3]
 [  1   0  16   0]
 [ 22   0 214   4]
 [  2   0   6   2]]


In [64]:
# KNN
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
knn_accuracy = accuracy_score(y_test, y_pred)
knn_cm = confusion_matrix(y_test, y_pred)
print(f'knn 정확도 {knn_accuracy:.2f}')
print(knn_cm)

knn 정확도 0.91
[[ 68   7   4   0]
 [  4  12   1   0]
 [ 13   0 227   0]
 [  1   0   0   9]]
